INSERT INTO municities (name, province_id) VALUES
('Aloran', 55),
('Baliangao', 55),
('Bonifacio', 55),
('Calamba', 55),
('Clarin', 55),
('Concepcion', 55),
('Don Victoriano Chiongbian', 55),
('Jimenez', 55),
('Lopez Jaena', 55),
('Oroquieta City', 55),
('Ozamiz City', 55),
('Panaon', 55),
('Plaridel', 55),
('Sapang Dalaga', 55),
('Sinacaban', 55),
('Tangub City', 55),
('Tudela', 55);
