-- Barangays for Aloran (municity_id: 1)
INSERT INTO barangays (name, municity_id) VALUES
('Bagsakan', 1),
('Bañadero', 1),
('Baybay', 1),
('Bungabong', 1),
('Caniangan', 1),
('Caputol', 1),
('Ciriaco Cañadido', 1),
('Dulapo', 1),
('Ebcoran', 1),
('Lake Duminagat', 1),
('Lamesa', 1),
('Manabay', 1),
('Panalsalan', 1),
('Paypayan', 1),
('San Roque', 1),
('Sebasi', 1),
('Silanga', 1),
('Taguima', 1),
('Taguitic', 1),
('Talic', 1),
('Taluc', 1);

-- Barangays for Baliangao (municity_id: 2)
INSERT INTO barangays (name, municity_id) VALUES
('Del Pilar', 2),
('Landing', 2),
('Lumipac', 2),
('Mahayag', 2),
('Misom', 2),
('Poblacion', 2),
('Salug', 2),
('Tugas', 2);

-- Barangays for Bonifacio (municity_id: 3)
INSERT INTO barangays (name, municity_id) VALUES
('Bag-ong Anonang', 3),
('Bag-ong Dalaguete', 3),
('Bag-ong Maslog', 3),
('Calao', 3),
('Dicoloc', 3),
('Liloan', 3),
('Lumanan', 3),
('Maluga-an', 3),
('Map-an', 3),
('Nasa', 3),
('Pangabuan', 3),
('Poblacion', 3),
('Roxas', 3),
('Santa Cruz', 3),
('Santa Rita', 3),
('Saripongpong', 3),
('Sibucao', 3),
('Silangit', 3),
('Tuno', 3),
('Upper Dapitan', 3);

-- Continue adding similar INSERT statements for other municipalities or cities

-- Barangays for Calamba (municity_id: 4)
INSERT INTO barangays (name, municity_id) VALUES
('Bunawan', 4),
('Calaran', 4),
('Dapacan Alto', 4),
('Dapacan Bajo', 4),
('Don Bernardo A. Neri', 4),
('Langub', 4),
('Libato', 4),
('Magcamiguing', 4),
('Mamalad', 4),
('Mantic', 4),
('Mauswagon', 4),
('North Poblacion', 4),
('Rizal', 4),
('San Isidro', 4),
('Solinog', 4),
('South Poblacion', 4),
('Sulipat', 4),
('Sumbot', 4),
('Tula', 4),
('Waterfall', 4);

-- Barangays for Clarin (municity_id: 5)
INSERT INTO barangays (name, municity_id) VALUES
('Agusipan', 5),
('Bato', 5),
('Bitoon', 5),
('Canibungan Proper', 5),
('Canibungan Ubos', 5),
('Dalingap', 5),
('Dela Paz', 5),
('Dolipos Alto', 5),
('Dolipos Bajo', 5),
('Labanan', 5),
('Lapasan', 5),
('Mabuhay', 5),
('Mialem', 5),
('Miasin', 5),
('Panalsalan', 5),
('Panaytayon', 5),
('Penacio', 5),
('Sebasi', 5),
('Segatic Daku', 5),
('Segatic Diot', 5),
('Tuyabang Alto', 5),
('Tuyabang Bajo', 5),
('Tuyabang Proper', 5);

-- Barangays for Concepcion (municity_id: 6)
INSERT INTO barangays (name, municity_id) VALUES
('Bagong Nayon', 6),
('Poblacion', 6),
('Guimad', 6),
('Deboloc', 6),
('Magbay', 6),
('Punta', 6),
('Santa Cruz', 6),
('San Isidro', 6),
('San Vicente', 6),
('Tonggo', 6),
('Upper Lumintao', 6);

-- Barangays for Don Victoriano (municity_id: 7)
INSERT INTO barangays (name, municity_id) VALUES
('Lake Duminagat', 7),
('Lalud', 7),
('Libertad Bajo', 7),
('Maramara', 7),
('Napangan', 7),
('Nueva Vista', 7),
('Pedacon', 7),
('Penacio', 7),
('San Isidro', 7),
('Sitio Litik', 7),
('Tuno', 7),
('Lalud Proper', 7),
('Lalud-Ext.', 7);

-- Barangays for Jimenez (municity_id: 8)
INSERT INTO barangays (name, municity_id) VALUES
('Butuay', 8),
('Corrales', 8),
('Dicoloc', 8),
('Diorog', 8),
('Malibacsan', 8),
('Matugas Alto', 8),
('Matugas Bajo', 8),
('Palilan', 8),
('Pongol', 8),
('Santa Cruz', 8),
('Sebasi', 8),
('Seti', 8),
('Sinara Alto', 8),
('Sinara Bajo', 8),
('Tabo-o', 8),
('Tanaon', 8);

-- Barangays for Lopez Jaena (municity_id: 9)
INSERT INTO barangays (name, municity_id) VALUES
('Baga', 9),
('Bitoon', 9),
('Biasong', 9),
('Basirang', 9),
('Macabayao', 9),
('Mialem', 9),
('Molicay', 9),
('Molave', 9),
('Peniel', 9),
('Poblacion', 9),
('Sibuloc', 9),
('Sibugon', 9),
('Tambulig', 9),
('Ulo-tanga', 9),
('Victoria', 9),
('Bagong Daan', 9);


-- Barangays for Oroquieta City (municity_id: 10)
INSERT INTO barangays (name, municity_id) VALUES
('Apil', 10),
('Bunga', 10),
('Buntawan', 10),
('Buntawan Dianib', 10),
('Canubay', 10),
('Clarin Settlement', 10),
('Dolipos Alto', 10),
('Dolipos Bajo', 10),
('Dullan', 10),
('Igpanao', 10),
('Layawan', 10),
('Libertad', 10),
('Loboc', 10),
('Lower Langcangan', 10),
('Lubluban', 10),
('Malaubang', 10),
('Mialen', 10),
('Mobod', 10),
('Montol', 10),
('Paypayan', 10),
('Rizal', 10),
('Sebucal', 10),
('Taboc Sur', 10),
('Talic', 10),
('Talairon', 10),
('Talon', 10),
('Toliyok', 10),
('Upper Langcangan', 10),
('Victoria', 10),
('Villaflor', 10);

-- Barangays for Ozamiz City (municity_id: 11)
INSERT INTO barangays (name, municity_id) VALUES
('Aguada', 11),
('Bacahan', 11),
('Bagakay', 11),
('Balintawak', 11),
('Bañadero', 11),
('Baybay Santa Cruz', 11),
('Capucao Caniangan', 11),
('Capucao Proper', 11),
('Catadman', 11),
('Carmen Annex', 11),
('Carmen', 11),
('Cogon', 11),
('Dalupan', 11),
('Dimaluna', 11),
('Dolores', 11),
('Gango', 11),
('Kinuman Norte', 11),
('Kinuman Sur', 11),
('Labinay', 11),
('Lam-an', 11),
('Lamanlupa', 11),
('Lanao', 11),
('Malindang', 11),
('Malaubang', 11),
('Manabay', 11),
('Molicay', 11),
('Molicay Proper', 11),
('Polao', 11),
('San Antonio', 11),
('San Roque', 11),
('Sebucal', 11),
('Sibucao', 11),
('Tinago', 11),
('Triunfo', 11);


-- Barangays for Panaon (municity_id: 12)
INSERT INTO barangays (name, municity_id) VALUES
('Bagong Silang', 12),
('Baga', 12),
('Calube', 12),
('Camanse', 12),
('Canaan', 12),
('Crispin A. Gonzales', 12),
('Galusong', 12),
('Labo', 12),
('Lumbayao', 12),
('Minaulon', 12),
('Mobod', 12),
('Motic', 12),
('San Andres', 12),
('San Juan', 12),
('Santa Cruz', 12),
('Sebac', 12),
('Tiaman', 12),
('Tubo-Pait', 12);


-- Barangays for Plaridel (municity_id: 12)
INSERT INTO barangays (name, municity_id) VALUES
('Aguada', 13),
('Banocboc', 13),
('Buñog', 13),
('Calacapan', 13),
('Catarman', 13),
('Clarin', 13),
('Dela Paz', 13),
('Eastern Looc', 13),
('Ebona', 13),
('Katipunan', 13),
('Lutao', 13),
('Mabini', 13),
('Maligubaan', 13),
('Mangidkid', 13),
('Mangilay', 13),
('Masidlakon', 13),
('Mohon', 13),
('Northern Poblacion', 13),
('Panalsalan', 13),
('Pan-ay Dacong', 13),
('Pan-ay Diot', 13),
('Poblacion', 13),
('Rizal', 13),
('Santa Cruz', 13),
('Southern Looc', 13),
('Tipan', 13),
('Tipolo', 13),
('Western Looc', 13);


-- Barangays for Sapang Dalaga (municity_id: 14)
INSERT INTO barangays (name, municity_id) VALUES
('Baga', 14),
('Caluya', 14),
('Casul', 14),
('Dasa', 14),
('Dinas', 14),
('Liboron', 14),
('Lunao', 14),
('Lunginan', 14),
('Macabayao', 14),
('Manla', 14),
('Mialen', 14),
('Poblacion', 14),
('Salimpuno', 14),
('San Agustin', 14),
('San Isidro', 14),
('San Miguel', 14),
('Sibaroc', 14),
('Upper Dapitan', 14);


-- Barangays for Sinacaban (municity_id: 15)
INSERT INTO barangays (name, municity_id) VALUES
('Cabasagan', 15),
('Calaran', 15),
('Catarman', 15),
('Colupan Alto', 15),
('Dinas', 15),
('Estrella', 15),
('Poblacion', 15),
('San Lorenzo Ruiz', 15),
('San Vicente', 15),
('Silanga', 15),
('Sinonoc', 15),
('Tañon', 15),
('Tipan', 15),
('Tipolo', 15),
('Tuparan', 15),
('Upper Dioyo', 15),
('Upper Sinacaban', 15);


-- Barangays for Tangub City (municity_id: 16)
INSERT INTO barangays (name, municity_id) VALUES
('Aquino', 16),
('Balatacan', 16),
('Bintana', 16),
('Bucao', 16),
('Capalaran', 16),
('Caniangan', 16),
('Garang', 16),
('Guinabot', 16),
('Hoyohoy', 16),
('Kimat', 16),
('Labuyo', 16),
('Lorenzo Tan', 16),
('Manga', 16),
('Maloro', 16),
('Mantic', 16),
('Matugnao', 16),
('Migcanaway', 16),
('Migsale', 16),
('Pangabuan', 16),
('Pili', 16),
('Poblacion I', 16),
('Poblacion II', 16),
('Poblacion III', 16),
('Salimpuno', 16),
('Santa Cruz', 16),
('Santa Maria', 16),
('Santo Niño', 16),
('Silangit', 16),
('Sibaroc', 16),
('Sicade', 16),
('Sumpot', 16),
('Taguite', 16),
('Tuno', 16);


-- Barangays for Tudela (municity_id: 17)
INSERT INTO barangays (name, municity_id) VALUES
('Balon', 17),
('Barra', 17),
('Basirang', 17),
('Bongabong', 17),
('Buenavista', 17),
('Cabol-anonan', 17),
('Cahayag', 17),
('Camating', 17),
('Canibungan Proper', 17),
('Casilak San Agustin', 17),
('Centro Hulpa (Pob.)', 17),
('Centro Napu (Pob.)', 17),
('Centro Upper (Pob.)', 17),
('Calambutan Bajo', 17),
('Calambutan Settlement', 17),
('Duanguican', 17),
('Gala', 17),
('Gumbil', 17),
('Locso-on', 17),
('Maikay', 17),
('Maribojoc', 17),
('Mitugas', 17),
('Nailon', 17),
('Namut', 17),
('Napurog', 17),
('Pan-ay Diot', 17),
('San Nicolas', 17),
('Sebac', 17),
('Silongon', 17),
('Sinuza', 17),
('Taguima', 17),
('Tigdok', 17),
('Yahong', 17);




