INSERT INTO provinces (name, region) VALUES
('Ilocos Norte', 'Region I: Ilocos Region'),
('Ilocos Sur', 'Region I: Ilocos Region'),
('La Union', 'Region I: Ilocos Region'),
('Pangasinan', 'Region I: Ilocos Region'),

('Batanes', 'Region II: Cagayan Valley'),
('Cagayan', 'Region II: Cagayan Valley'),
('Isabela', 'Region II: Cagayan Valley'),
('Nueva Vizcaya', 'Region II: Cagayan Valley'),
('Quirino', 'Region II: Cagayan Valley'),

('Aurora', 'Region III: Central Luzon'),
('Bataan', 'Region III: Central Luzon'),
('Bulacan', 'Region III: Central Luzon'),
('Nueva Ecija', 'Region III: Central Luzon'),
('Pampanga', 'Region III: Central Luzon'),
('Tarlac', 'Region III: Central Luzon'),
('Zambales', 'Region III: Central Luzon'),

('Batangas', 'Region IV-A: CALABARZON'),
('Cavite', 'Region IV-A: CALABARZON'),
('Laguna', 'Region IV-A: CALABARZON'),
('Quezon', 'Region IV-A: CALABARZON'),
('Rizal', 'Region IV-A: CALABARZON'),

('Marinduque', 'Region IV-B: MIMAROPA'),
('Occidental Mindoro', 'Region IV-B: MIMAROPA'),
('Oriental Mindoro', 'Region IV-B: MIMAROPA'),
('Palawan', 'Region IV-B: MIMAROPA'),
('Romblon', 'Region IV-B: MIMAROPA'),

('Albay', 'Region V: Bicol Region'),
('Camarines Norte', 'Region V: Bicol Region'),
('Camarines Sur', 'Region V: Bicol Region'),
('Catanduanes', 'Region V: Bicol Region'),
('Masbate', 'Region V: Bicol Region'),
('Sorsogon', 'Region V: Bicol Region'),

('Aklan', 'Region VI: Western Visayas'),
('Antique', 'Region VI: Western Visayas'),
('Capiz', 'Region VI: Western Visayas'),
('Guimaras', 'Region VI: Western Visayas'),
('Iloilo', 'Region VI: Western Visayas'),
('Negros Occidental', 'Region VI: Western Visayas'),

('Bohol', 'Region VII: Central Visayas'),
('Cebu', 'Region VII: Central Visayas'),
('Negros Oriental', 'Region VII: Central Visayas'),
('Siquijor', 'Region VII: Central Visayas'),

('Biliran', 'Region VIII: Eastern Visayas'),
('Eastern Samar', 'Region VIII: Eastern Visayas'),
('Leyte', 'Region VIII: Eastern Visayas'),
('Northern Samar', 'Region VIII: Eastern Visayas'),
('Samar', 'Region VIII: Eastern Visayas'),
('Southern Leyte', 'Region VIII: Eastern Visayas'),

('Zamboanga del Norte', 'Region IX: Zamboanga Peninsula'),
('Zamboanga del Sur', 'Region IX: Zamboanga Peninsula'),
('Zamboanga Sibugay', 'Region IX: Zamboanga Peninsula'),

('Bukidnon', 'Region X: Northern Mindanao'),
('Camiguin', 'Region X: Northern Mindanao'),
('Lanao del Norte', 'Region X: Northern Mindanao'),
('Misamis Occidental', 'Region X: Northern Mindanao'),
('Misamis Oriental', 'Region X: Northern Mindanao'),

('Davao de Oro', 'Region XI: Davao Region'),
('Davao del Norte', 'Region XI: Davao Region'),
('Davao del Sur', 'Region XI: Davao Region'),
('Davao Occidental', 'Region XI: Davao Region'),
('Davao Oriental', 'Region XI: Davao Region'),

('Cotabato', 'Region XII: SOCCSKSARGEN'),
('Sarangani', 'Region XII: SOCCSKSARGEN'),
('South Cotabato', 'Region XII: SOCCSKSARGEN'),
('Sultan Kudarat', 'Region XII: SOCCSKSARGEN'),

('Agusan del Norte', 'Region XIII: Caraga'),
('Agusan del Sur', 'Region XIII: Caraga'),
('Dinagat Islands', 'Region XIII: Caraga'),
('Surigao del Norte', 'Region XIII: Caraga'),
('Surigao del Sur', 'Region XIII: Caraga'),

('Abra', 'Cordillera Administrative Region (CAR)'),
('Apayao', 'Cordillera Administrative Region (CAR)'),
('Benguet', 'Cordillera Administrative Region (CAR)'),
('Ifugao', 'Cordillera Administrative Region (CAR)'),
('Kalinga', 'Cordillera Administrative Region (CAR)'),
('Mountain Province', 'Cordillera Administrative Region (CAR)'),

('Basilan', 'Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)'),
('Lanao del Sur', 'Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)'),
('Maguindanao del Norte', 'Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)'),
('Maguindanao del Sur', 'Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)'),
('Sulu', 'Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)'),
('Tawi-Tawi', 'Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)');
